
function getLocalizedCaseByCount(num) {
	if (isNaN(num)) {
		return;
	}

const	absValue = Math.abs(num)
,	numPartUnder100 = absValue % 100
,	numPartUnder10 = absValue % 10
,	numPartFraction = absValue % 1
	;

	if (
		(numPartUnder100 > 10 && numPartUnder100 < 20)
	||	(numPartUnder10 !== 1)
	||	(numPartFraction > 0)
	) {
		return 'plural';
	}

	return 'singular';
}

const LOCALIZATION_TEXT = {
	'loading': 'Loading page...',

	'fixed_tab_width': 'Fixed tab width.',
	'larger_text': 'Larger text.',
	'text_size_sample': 'A',

	'about': 'About',

	'about_lang': 'This page in different languages',
	'about_source': 'Source code, discuss issues and requests',
	'about_notes': [
		'This page is a web application to preview and export multiple artwork variants from a single project file.',
		'The variants must be prepared by the author of the file. The Manual section describes how to.',
		,
		'Chrome-based browsers are recommended for this page.',
		'For example, Firefox works with colors premultiplied with alpha for faster display and composition.',
		'This hurts blending precision and results in color-banded gradients, which were supposed to be smooth.',
		'It is planned later to add custom high-precision rendering without relying on browser built-in methods.',
		'As of version 83, Firefox still does not support indentation in generated XML (used in ORA export here).',
		'Older Firefox versions (e.g. 56) may hang on trying to save generated blob files.',
		,
		'This page does not preload all its program libraries at start, but adds them when needed.',
		'So a network disconnect may prevent it from working when the page is hosted on a remote server.',
		'On the other hand, the page works fine from disk.',
		'So you may take a full copy of the code from GitHub and use it locally, even without the internet.',
	],

	'file': 'File',

	'file_select_project': 'Drag and drop a project file onto this page, or select here',
	'file_formats': 'Supported file types',
	'file_notes': [
		'Notes:',
		'This page never sends any files or other data to the internet.',
		'All work and settings remain inside your browser.',
		,
		'File types mentioned in brackets are accepted if their content is conforming to the main type.',
		'Using project files saved in a maximum compatibility mode is recommended.',
		,
		'If multiple files with same name are opened, earlier ones will close.',
	],

	'examples': 'Examples',

	'examples_notice': [
		'Notice:',
		'The files here are only for reference.',
		'Do not reuse without permission.',
	],

	'psd_from_sai2': 'SAI2 → PSD as is',
	'ora_export': 'SAI2 → PSD → this page → ORA → Leanify (keeping stack.xml)',
	'ora_mockup': 'SAI2 → PSD → Krita (no clipping) → ORA (no masks) → manual fixes',
	'from_paint.net': 'paint.net (with plugins) → PSD and ORA as is (no folders)',

	'help': 'Manual',

//* These parts are only used inside this file and may be added or removed as needed:

	'help_common_part_add_all_default': 'Shorthand to add all default variants',
	'help_common_part_default_added': 'If no valid variants were found anywhere in the file, default variants are added automatically.',
	'help_common_part_default_for_all': 'If no explicit setting was found, this is default for all options.',
	'help_common_part_each_identifier_added': 'Each list and option identifier, separated by comma, is added separately.',
	'help_common_part_each_list_identifier_added': 'Each list identifier, separated by comma, is added separately.',
	'help_common_part_global_param': 'This parameter works globally, no matter where it is added.',
	'help_common_part_slash_separated': 'All valid slash-separated variants are added as options.',

//* And further parts are needed for the code outside of this file:

	'help_code_alias': 'some-alias',
	'help_code_child_name': 'Child Name',
	'help_code_child_param': 'child parameters',
	'help_code_color_value': 'color-value',
	'help_code_comment': 'comment',
	'help_code_copy': 'Copy',
	'help_code_folder': 'Folder',
	'help_code_layer': 'Layer',
	'help_code_layer_to_recolor': 'Layer to recolor',
	'help_code_list_folder': 'List folder',
	'help_code_list_name': 'List Name',
	'help_code_list_name_colors': 'Color List Name',
	'help_code_list_name_opacity': 'Opacity List Name',
	'help_code_list_name_padding': 'Outline List Name',
	'help_code_list_name_parts': 'Part List Name',
	'help_code_more_comments': 'more comments',
	'help_code_more_folders': 'more folders',
	'help_code_more_layers': 'more layers',
	'help_code_more_numbers': 'more-numbers',
	'help_code_more_values': 'more-values',
	'help_code_name': 'Name',
	'help_code_option_folder': 'Option folder',
	'help_code_option_inverted': 'Inverted option',
	'help_code_option_layer': 'Option layer',
	'help_code_option_name': 'Option Name',
	'help_code_option_name_color': 'Color Name',
	'help_code_option_name_color_same': 'Same Color Name',
	'help_code_option_name_part': 'Part Name',
	'help_code_option_nested': 'Nested option layer',
	'help_code_otherwise': 'otherwise',
	'help_code_param': 'parameter',
	'help_code_parent_name': 'Parent Name',
	'help_code_parent_param': 'parent parameters',
	'help_code_section_name': 'type',
	'help_code_separate_group_name': 'Separate Group Name',

	'help_autocrop': 'Autocrop',
	'help_autocrop_notes': [
		'Autocrop removes bar areas filled with given color around rendered image.',
		,
		'{help_common_part_global_param}',
		'{help_common_part_slash_separated}',
		'{help_common_part_default_added}',
	],
	'help_autocrop_all': 'Shorthands to add all corners and completely transparent variants.',
	'help_autocrop_color': 'See the section {0}.',
	'help_autocrop_corner': 'Pick color value from pixel in the given corner of the image.',
	'help_autocrop_default': [
		'{help_common_part_add_all_default}:',
		'{0}',
	],

	'help_batch': 'Batch and layout',
	'help_batch_notes': [
		'For batch and collage rendering — these parameters affect initial settings for each option list.',
		'These parameters only work when added directly on a layer or folder which is an option list.',
		,
		'For example:',
		'{0}',
		,
		'First found explicit setting makes the inverse to be global default for all other option lists in the file.',
	],
	'help_batch_all': [
		'Create images for each option of this list, selected or not.',
		'{help_common_part_default_for_all}',
	],
	'help_batch_single': 'Use only the single selected option.',
	'help_batch_omitable': '{hint_switch_option_omitable}',
	'help_batch_unomitable': '{hint_switch_option_unomitable}',
	'help_batch_inline': [
		'Images are shown in a single line from left to right.',
		'{help_common_part_default_for_all}',
		,
		'For batch — automatic line wrapping of the page is used.',
		'For collage — no line wrapping is used.',
	],
	'help_batch_newline': [
		'Images for each variant from this list go to a separate line.',
		'If image count and width is equal for each line, it will result in uniform columns.',
	],

	'help_clone': 'How to reuse layer clones in multiple places',
	'help_clone_notes': [
		'Mark source layers to copy, and places to paste them to, with some arbitrary matching keywords.',
		'Keywords from this parameter context are global and independent from anything else.',
	],
	'help_clone_copy': 'Mark source layers or folder to be copied with "{0}" keyword.',
	'help_clone_paste': [
		'Mark places to paste copies matching "{0}" keyword.',
		,
		'This may be any layer or folder, empty or not.',
		'If not empty, it is rendered first below the copies.',
	],
	'help_clone_paste_above': 'Paste above layer content and all copies added with simple {0}.',
	'help_clone_paste_below': 'Paste below layer content and all copies added with {0} or {1}.',
	'help_clone_layer_names': 'Use identifiers from the layer name.',
	'help_clone_empty_id': 'Use empty text as keyword.',
	'help_clone_multi_copy': 'Use any of given keywords to match this source layer.',
	'help_clone_multi_paste': [
		'Paste a source layer copy for each matched keyword in given order.',
		'If several keywords point to the same source layer, it will be pasted only once.',
	],

	'help_collage': 'Collage',
	'help_collage_notes': [
		'Collage joins images rendered as a batch into one image.',
		,
		'{help_common_part_global_param}',
		'{help_common_part_slash_separated}',
		'{help_common_part_default_added}',
	],
	'help_collage_all': 'Shorthands to add all alignment variants.',
	'help_collage_align': [
		'Horizontal alignment of joined image rows.',
		'Vertical alignment of images inside the rows.',
	],
	'help_collage_border': 'Width of border around the whole collage, as number of pixels.',
	'help_collage_padding': 'Width of padding between neighbour joined images, as number of pixels.',
	'help_collage_pixels': 'Add both border and padding variants, as number of pixels.',
	'help_collage_color': 'Background fill color. See the section {0}.',
	'help_collage_default_align': 'Alignment',
	'help_collage_default_colors': 'Background',
	'help_collage_default_padding': 'Padding',
	'help_collage_default': [
		'{help_common_part_add_all_default}:',
		'{0}',
	],

	'help_color_value': 'Color fill and color value formats',
	'help_color_value_notes': [
		'A standalone color value parameter without any prefix or suffix means the layer fill color.',
		'When using fill color, the actual layer content is ignored, if any.',
		'This allows to spend less time when loading the file, or lessen the file size using layers without contents.',
		,
		'Several formats are supported, including standard {1}, e.g. "Red", "DarkBlue", "LightGray", etc.',
		'Dashes in color names are allowed and may be added for clarity, e.g. "dark-red".',
		,
		'In the following table each row has equivalent value in all columns:',
		'{0}',
	],
	'help_color_value_names_link': 'https://en.wikipedia.org/wiki/Web_colors',
	'help_color_value_names_link_text': 'web color names',
	'help_color_value_table_short_hex': 'Hex shorthand',
	'help_color_value_table_split_hex': 'Hex by channels',
	'help_color_value_table_split_dec': 'Decimal by channels',
	'help_color_value_transparent': 'Completely transparent, equivalent to this value: {0}.',
	'help_color_value_short_hex': [
		'Hexadecimal shorthand format, 1 or 2 symbols per channel in RGBA order.',
		'For consistent results all channels in a color value should have the same number of symbols.',
	],
	'help_color_value_split_hex': [
		'Hexadecimal format, separated by channels in RGBA order.',
		'Each channel value is from 0 to FF (equal to decimal 255).',
		'Values are made of digits from 0 to 9 and letters from A to F (equal to decimal from 10 to 15).',
	],
	'help_color_value_split_dec': [
		'Decimal format, separated by channels in RGBA order &mdash; red, green, blue (colors), alpha (opacity).',
		'Each channel value is from 0 to 255.',
		'Values are made of digits from 0 to 9.',
		'Omitted colors are assumed to be 0.',
		'Omitted opacity is assumed to be 255 (completely non-transparent).',
	],

	'help_colors': 'Variable coloring',
	'help_colors_notes': [
		'Like parts, colors are added as layers in color list folders.',
		,
		'When rendering, each color list folder is replaced with the whole image area filled with selected color.',
		'This may be used with layer clipping. Note that some programs do not support clipping mode on folders.',
		,
		'Color lists also may be put into some place that will not be rendered, to only collect values for recoloring rendered layers.',
		'{0} may be used for this. See the section {1}.',
		,
		'Other layers and folders that are not a color list, but have any matching name identifiers, are recolored to selected color.',
		'Transparency (alpha channel) is kept as is, the same way as using layer clipping mode.',
		'Parameters are not needed to recolor, only a layer name that equals a color list name.',
		,
		'For example:',
		'{2}',
		,
		'Color list ignores its layer visibility setting from the project file.',
		'If empty value is selected, color list folders are skipped over, while matching layers are not recolored and used as is.',
		,
		'Color value of each option layer is taken from its parameter or top-left pixel of its content.',
		'See the section {3}.',
	],
	'help_colors_add': [
		'{help_common_part_each_identifier_added}',
		'This way, some collection of colors may be added to multiple lists at once.',
	],
	'help_colors_nested': [
		'Any layer with pixel content or defined color value is added to the list as option from anywhere inside a color list folder.',
	],
	'help_colors_path_logic': [
		'An option may have multiple colors to use under one name with nested layer path logic.',
		'First layer from top to bottom that passes its path logic is used for rendering.',
		,
		'Path logic with {0} applies to list rendering choices even without {1}.',
		'See the section {2}.',
	],

	'help_naming_order': 'File names for saving',
	'help_naming_order_notes': [
		'Define initial order of variants in names of saved image files.',
		'This order may be modified or reset later in the project file naming menu.',
		,
		'All selected variants are grouped by type and may be reordered only inside their group.',
		'The groups may be reordered as whole.',
		,
		'Parameter values are separated by forward slashes, {0}.',
		'All values may be added in one set, for example:',
		'{1}',
		,
		'Parameter values may be added as shortcuts, matched by prefix, for example:',
		'{2}',
		'But this is not recommended for compatibility.',
		'If matching order changes in future, ambiguous shortcuts can change effective meaning.',
		,
		'{help_common_part_global_param}',
		,
		'By default, groups are ordered as in table below, and grouped variants are autosorted.',
	],
	'help_naming_order_table_section_title': 'Option type',
	'help_naming_order_table_section_name': 'Parameter value',
	'help_naming_order_sort': 'Auto-sort groups and variants in them alphabetically.',
	'help_naming_order_sort_sections': 'Auto-sort type groups by their type parameter from the table below.',
	'help_naming_order_sort_options': 'Auto-sort variants in each group by variant list names.',
	'help_naming_order_given_sections': 'Order type groups as encountered in the project file.',
	'help_naming_order_given_options': 'Order variants in each group as encountered in the project file.',
	'help_naming_order_given': [
		'Order groups and variants as encountered in the project file.',
		,
		'Specific order of encounter may be redefined inside a preceeding {0} folder.',
		'See the section {1}.',
	],
	'help_naming_order_names': [
		'Order list groups as given in slash-separated parameter values.',
		'This overrides anything else, pushing given values to the start of filename.',
		,
		'Following type values are valid, here in default order:',
		'{0}',
	],

	'help_opacity': 'Variable opacity and transparency',
	'help_opacity_notes': [
		'Opacity of every layer or folder with a matching name may be set to selected value.',
	],
	'help_opacity_set': [
		'{help_common_part_slash_separated}',
		'{help_common_part_each_list_identifier_added}',
		,
		'A layer, that has any of identifiers of the list, will use the selected opacity value.',
		'If empty value is selected, matching layers use opacity setting from the project file.',
		,
		'Only values from 0% to 100% are valid.',
		,
		'0% is not an empty value, for which {0} is used. See the section {1}.',
		'0% opacity means that the layer is completely transparent, i.e. not shown at all.',
	],

	'help_other': 'Other parameters',
	'help_other_optional': 'Used with any kind of option list, add empty option to the end.',
	'help_other_last': 'Select last option initially, empty or not.',
	'help_other_preselect': 'Select this option initially.',
	'help_other_prefix': [
		'In saved file names — add list title prefix to selected variant.',
		,
		'For example:',
		'{0}',
		,
		'All other options will be unprefixed by default.',
	],
	'help_other_no_prefix': [
		'In saved file names — use variant names without list title prefix.',
		,
		'For example:',
		'{0}',
		,
		'All other options will be prefixed by default.',
	],
	'help_other_no_render': [
		'Skip this layer or folder when rendering.',
		'This is useful for organizing collection of options separately from artwork content.',
		,
		'Note that any layers clipped to a layer which is not rendered will be skipped too.',
	],
	'help_other_skip': [
		'Skip this layer or folder in any context, i.e. reading the file, collecting options and rendering images.',
		'This is useful for disabling things, but keeping a backup of their content in the project file.',
		,
		'Note that any layers clipped to a layer which is not used will be skipped too.',
	],

	'help_padding': 'Variable outlines',
	'help_padding_notes': [
		'Outline is made of filler, which is cut into a form of outlined content plus some padding around.',
		,
		'Form generation layer must be placed under all the content that is intended to be outlined.',
		'Content of form generation layer becomes the outline color fill or pattern.',
		,
		'Pre-existing mask of form generation layer from the project file is ignored, if any.',
		'If empty value is selected, the whole fill content will be rendered.',
		,
		'All valid padding variants are added as options.',
	],
	'help_padding_outer_radius': [
		'Add round padding up to given radius away from each visible pixel of outlined content.',
		,
		'Variants of padding are separated by forward slashes, {0}.',
		'Variants of numbers are separated by commas or ellipsis (multiple dots).',
		'Ellipsis defines a whole range of variants, counting from the left number to the right.',
		,
		'Nested round brackets demonstrate how values are grouped.',
		'They are optional and may be added for readability.',
		'Adding whitespace inside round brackets will break the parameter.',
	],
	'help_padding_inner_radius': [
		'Add round padding using the greater number in the selected pair as outer radius.',
		'Then take a cut inside the padding using the lesser number as inner radius.',
		'Width of the outline is the difference between these two numbers.',
		,
		'Inner and outer dimensions are separated by a colon, {0}.',
		'An option is added for each possible pair of numbers, one before the colon and one after.',
		,
		'If one side of colon is empty, outer and inner radius are equal.',
		'Outline may become very thin, but still visible.',
	],
	'help_padding_outer_box': [
		'Add box padding, using maximum visibility (alpha) values within width and height vicinity of each pixel.',
		'Horizontal and vertical dimensions are separated by letter {0}.',
	],
	'help_padding_inner_box': 'Add box padding defined by inner and outer width and height vicinity.',
	'help_padding_outer_square': 'If one side of dimensions is empty, the box is square, i.e. its width and height vicinity are equal.',
	'help_padding_inner_square': [
		'If one side of dimensions has empty inner or outer vicinity, it is equal to that of the other dimension.',
		'If both sides have empty inner value, it is equal to the outer.',
		'If all values are empty, the variant is not valid.',
	],
	'help_padding_invalid': 'This syntax is not valid an will be taken as {0}.',
	'help_padding_threshold': [
		'Visible alpha threshold variants, as numbers from 0 to 255.',
		'For the outlined content — only pixels with alpha channel value greater than this number are considered visible.',
		'This is useful to not outline almost erased areas of rough sketchy artwork, which are not visible to humans.',
	],
	'help_padding_cross': [
		'Options will be added for all combinations of all variants of all types in one slash-separated block.',
		,
		'If a block has valid variants of some types, but not of every type:',
		'Default dimension is {0}px radius.',
		'Default alpha threshold is {1}.',
	],

	'help_param': 'How to add options and parameters',
	'help_param_names': 'Identifiers',
	'help_param_params': 'Parameters',
	'help_param_comments': 'Comments',
	'help_param_notes': [
		'Write parameters as text in layer names in a project file.',
		,
		'Parts of layer names that have meaning:',
		'{1} are inside square brackets and separated from each other by spaces.',
		'{2} are inside round brackets and skipped over, they are meant for people.',
		'{3} are outside of any brackets, separated from each other by commas, slashes or parts in brackets.',
		'{4} (forward slashes) are virtual path separators. See the section {0}.',
		,
		'Layer names are interpreted in the following way:',
		'1. Find the first or nearest opening bracket (square or round).',
		'2. Then the nearest closing bracket of matching type regardless of anything inbetween.',
		'And so on.',
		,
		'Nested square brackets have no meaning, but can break things around them and should not be used.',
		'Nested round brackets are safe for some parameters, as shown in examples, and are optional for readability.',
		'Empty parts (zero-length or whitespace-only) are skipped.',
		,
		'The following examples are equivalent:',
		'{5}',
		,
		'Order of options follows the order of identifiers and parameters from left to right and layers from top to bottom.',
		,
		'For logical combinations of parameters within one layer — their order and place does not matter, even if separated.',
		'But it is not recommended to put conflicting parameters and expect it to work consistently one way or the other.',
		,
		'Some types of parameters can have effect in various ways:',
		'Global, related to the whole layer tree, rendered image or the project file.',
		'Path-local, related to location of this layer in the tree.',
		'Self-contained, related to other parameters or properties of this layer.',
	],

	'help_parts': 'Variable parts and visibility',
	'help_parts_notes': [
		'Parts are layers and folders inside list folders, with selection which one to show via menu.',
		'All layers or folders directly inside a list folder are added to the list as options.',
		,
		'For example:',
		'{0}',
		,
		'When no relevant layers would be shown with an option, it is hidden from menu.',
		'Part list and the parts directly inside ignore their layer visibility setting from the project file.',
	],
	'help_parts_add': [
		'{help_common_part_each_identifier_added}',
		,
		'Path logic with {0} applies to list rendering choices even without {1}.',
		'See the section {2}.',
	],

	'help_path_logic': 'Layer path logic',
	'help_path_logic_notes': [
		'{0} is used for layer path logic and does not add options to selectable list.',
		'Layer that uses path logic ignores its visibility setting from the project file.',
	],
	'help_path_logic_if': 'Option layer is rendered if any of its identifiers match the selected option of the list.',
	'help_path_logic_if_not_option': 'Invert the logic. Option layer is rendered if none of its identifiers match the selection.',
	'help_path_logic_if_not_list': '{0} on list folder inverts the logic for each nested option.',
	'help_path_logic_if_not_both': '{0} on both list folder and option layer inverts the logic twice.',
	'help_path_logic_if_any': 'This layer is rendered if any identifiers match a list name that has non-empty option selected.',
	'help_path_logic_if_not_any': 'Invert the logic. Layer is rendered if none of identifiers match a list with non-empty selection.',
	'help_path_logic_any': 'No effect without {0}.',
	'help_path_logic_not': 'Same effect on lists and options without {0} or {1}.',
	'help_path_logic_none': `Equivalent to empty option, adds empty name to layer's option identifiers.`,

	'help_separate': 'How to show parts separately',
	'help_separate_alias_id': [
		'Add options to separately render each layer directly inside marked folder.',
		'Attach the layers to a group named "{0}" for selection filtering in menu.',
		,
		'Here and below, in saved file names — use equal variant naming by default.',
	],
	'help_separate_equal': [
		'Use equal variant naming.',
		,
		'For example:',
		'{0}',
	],
	'help_separate_numbered': [
		'Use numbered variant naming.',
		,
		'For example:',
		'{0}',
	],
	'help_separate_layer_names': 'Use identifiers from the layer name as group names.',
	'help_separate_empty_id': 'Use empty text as a group name.',
	'help_separate_global': [
		'Find the branching root automatically.',
		'It will be the topmost level in the project file with more than one renderable layers or folders on it.',
		,
		'In saved file names — use numbered variant naming by default.',
		'{help_common_part_global_param}',
	],
	'help_separate_notes': 'All renderable layers or folders directly on a branching root are added as options.',

	'help_side': 'Variable view side and flipping',
	'help_side_notes': 'Any of these parameters will add two global options, to select a front or back view side.',
	'help_side_front': 'For front view — show this layer, hide otherwise, ignoring layer visibility setting.',
	'help_side_back': 'For back view — show this layer, hide otherwise, ignoring layer visibility setting.',
	'help_side_reverse': [
		'For back view — layers directly inside this folder will be merged in reverse order.',
		'This applies with flip variants too.',
		,
		'To avoid reordering of layers with clipping or blending modes, group them in a passthrough subfolder.',
	],
	'help_side_flip_hor': 'For back view — horizontally flip layer content or merged folder image.',
	'help_side_flip_ver': 'For back view — vertically flip layer content or merged folder image.',

	'help_virtual_path': 'How to add nested layer paths without creating folders',
	'help_virtual_path_notes': [
		'Virtual path is written in the name of a layer or folder, as parts separated by forward slashes.',
		'Parameters in each part are applied to that part as if it was a nested folder.',
		,
		'For example:',
		'{0}',
		,
		'For parameters — it means the same as following:',
		'{1}',
		,
		'For rendering — the real layer or folder becomes the last child of the virtual path.',
		'It is nested in dummy pass-through folders per the rest of its virtual path parts.',
		'Clipping mode, if enabled, is applied to the first parent.',
		,
		'Virtual path structures are one layer wide towers.',
		'If real folders cannot be used, it may be worked around using layer-pasting parameters.',
		'See the section {2}.',
	],

	'help_zoom': 'Variable image scale',
	'help_zoom_notes': [
		'Rendered images will be scaled by the selected factor.',
		'All intermediate scaling steps are cached.',
		,
		'{help_common_part_global_param}',
		'{help_common_part_slash_separated}',
		,
		'Only values greater than 0% are valid.',
		,
		'Empty option, added with {0}, has the same effect as 100%.',
		'See the section {1}.',
	],

	'open_section': 'Open',
	'close_section': 'Close',
	'open_all_sections': 'Open all sections',
	'close_all_sections': 'Close all sections',

	'save_all_projects': 'Save all opened projects',
	'save_all_ora': 'Save to ORA',
	'save_all_png': 'Save to PNG',
	'save_all_png_batch': 'Save all variants to PNG',

	'close_all_projects': 'Close all opened projects',
	'close_all_with_no_var': 'Only with no variants',
	'close_all_with_errors': 'Only with errors',
	'close_all': 'Close all',

	'download_file': 'Download file',
	'download_all': 'Download all',
	'open_example_file': 'Show example',
	'open_example_all': 'Show all',
	'stop': 'Stop (Esc)',

	'open_same_name': 'If opening file has the same name as one of already opened',
	'ask': 'Ask',
	'skip': 'Skip',
	'replace': 'Replace',
	'replace_old': 'Replace if older',

	'file_bytes': '{0} bytes',
	'file_date': 'last modified {0}',

	'project_bits': '{0} bit',
	'project_bits_channels': '{0}x{1} bit',
	'project_channels_plural': '{0} channels',
	'project_channels_singular': '{0} channel',
	'project_folders_plural': '{0} folders',
	'project_folders_singular': '{0} folder',
	'project_images_loaded_all_plural': '{0} images or masks loaded',
	'project_images_loaded_all_singular': '{0} image or mask loaded',
	'project_images_loaded_plural': '{0} of {1} images or masks loaded',
	'project_images_loaded_singular': '{0} of {1} image or mask loaded',
	'project_images_plural': '{0} images or masks',
	'project_images_singular': '{0} image or mask',
	'project_layers_plural': '{0} layers',
	'project_layers_singular': '{0} layer',
	'project_pixels_plural': '{0}x{1} pixels',
	'project_pixels_singular': '{0}x{1} pixel',

	'show_project_details': 'Show internal details',

	'reset_header': 'Reset all options and switches',
	'reset_options_header': 'Reset all options',
	'reset_options_to_init': 'To initial',
	'reset_options_to_top': 'To top',
	'reset_options_to_bottom': 'To bottom',
	'reset_options_to_empty': 'To empty where possible',

	'reset_switch_header': 'Reset all switches',
	'reset_switch_batch_to_batched': 'All batches',
	'reset_switch_batch_to_single': 'No batches',
	'reset_switch_layout_to_inline': 'All in row',
	'reset_switch_layout_to_newline': 'All in column',
	'reset_switch_option_to_omitable': 'Omit single option names',
	'reset_switch_option_to_unomitable': 'Add all options to filename',
	'reset_switch_prefix_to_prefixed': 'Add option group prefixes',
	'reset_switch_prefix_to_unprefixed': 'Omit option group prefixes',

	'original_view_header': 'Original project file view',
	'show_original_png': 'Show',
	'save_original_png': 'Save to PNG',
	'save_original_ora': 'Save to ORA (with all layers)',

	'current_view_header': 'Selected options',
	'show_png': 'Show',
	'save_png': 'Save to PNG',
	'save_ora': 'Save to ORA (only used layers)',

	'batch_view_header': 'Selected batch',
	'batch_counting': 'Evaluating ... {0} / {1}',
	'batch_count': '{0} variants',
	'batch_count_singular': '{0} variant',
	'show_png_batch': 'Show all',
	'save_png_batch': 'Save all to PNG',
	'save_png_batch_zip': 'Save all to ZIP',
	'show_png_collage': 'Show collage',
	'save_png_collage': 'Save collage to PNG',

	'saved_file_naming_preview': 'Current image name to save',
	'saved_file_naming_change': 'Change naming order',
	'saved_file_naming_close': 'Close',
	'saved_file_naming_sort': 'Sort alphabetically',
	'saved_file_naming_reset_to_initial': 'Restore project default',
	'saved_file_naming_reset_to_default': 'Reset to page default',

	'option_header_collage': 'Collage',
	'option_header_view': 'View',
	'option_header_separate': 'Separate parts',
	'option_header_parts': 'Visible parts',
	'option_header_opacities': 'Transparent parts',
	'option_header_paddings': 'Outlines and paddings',
	'option_header_colors': 'Colors',

	'option_collage_align': 'align rows',
	'option_collage_background': 'background color',
	'option_collage_border': 'border around',
	'option_collage_padding': 'padding inbetween',

	'option_autocrop': 'autocrop around',
	'option_zoom': 'scale',
	'option_side': 'side',

	'option_separate': 'separate',
	'option_separate_naming': 'file naming',
	'option_separate_group': 'group',
	'option_separate_part': 'part',

	'align_bottom': 'bottom',
	'align_bottomleft': 'bottom-left',
	'align_bottomright': 'bottom-right',
	'align_left': 'left',
	'align_right': 'right',
	'align_top': 'top',
	'align_topleft': 'top-left',
	'align_topright': 'top-right',

	'background_color': 'color',
	'background_transparent': '100% transparent',

	'autocrop_by_color': 'color',
	'autocrop_bottomleft': 'bottom-left color',
	'autocrop_bottomright': 'bottom-right color',
	'autocrop_topleft': 'top-left color',
	'autocrop_topright': 'top-right color',
	'autocrop_transparent': '100% transparent',

	'side_front': 'front',
	'side_back': 'back',

	'switch_batch_batched': 'all',
	'switch_batch_single': 'single',
	'switch_layout_inline': 'inline',
	'switch_layout_newline': 'newline',
	'switch_option_omitable': 'omitable',
	'switch_option_unomitable': 'unomitable',
	'switch_prefix_prefixed': 'prefixed',
	'switch_prefix_unprefixed': 'unprefixed',

	'hint_switch_batch_batched': 'Use this whole list for batch view/save.',
	'hint_switch_batch_single': 'Use only one selected option for batch view/save.',
	'hint_switch_layout_inline': 'Keep images in collage for each options in this batch in one row.',
	'hint_switch_layout_newline': 'Make a new row of images in collage for each option in this batch.',
	'hint_switch_option_omitable': 'In saved file names — add option name in batch mode, but omit in single mode.',
	'hint_switch_option_unomitable': 'In saved file names — always add option name, in batch and single modes.',
	'hint_switch_prefix_prefixed': 'In saved file names — add option group name, e.g. "{filename_option_group}".',
	'hint_switch_prefix_unprefixed': 'In saved file names — add selected option without group name, e.g. "{filename_option}".',

	'hint_menu': 'Left click to lock this menu open or unlock.',
	'hint_canvas': 'Right click to save result image.',
	'hint_close_tab': 'Close this project.',
	'confirm_close_page': 'Close all projects on this the page?',
	'see_console': 'See in the browser console.',
	'no_options': 'Project without options.',
	'too_many': 'Too many',
	'too_much': 'Too much',

	'separate_naming_numbered': 'file[option_group_(1)_variant][...].png',
	'separate_naming_equal': 'file[option_group=variant][...].png',

	'filename_option': 'file[variant][...].png',
	'filename_option_group': 'file[option_group=variant][...].png',

	'render_took_time': 'rendering this image took {0} sec.',
	'collage_took_time': 'joining {1} images took {0} sec.',

	'error_js_features': [
		'HTML5 Canvas or some other required JS features are not supported in your web browser program.',
		'Project rendering will not work, but you still can browse the links or download example files.',
	],
	'error_canvas_size': [
		'Cannot create a canvas of required size: {0}.',
		'Try selecting less images or splitting long rows.',
	],
	'error_file_protocol': [
		'Cannot load files from disk via page request, because of security concerns.',
		'Try using the "{0}" menu in the top of the page.',
	],

	'project_status_error': 'Error.',
	'project_status_error_file_type': 'Unsupported file type "{0}".',
	'project_status_error_in_format': 'Error in file content.',
	'project_status_error_in_layers': 'Error in layers.',
	'project_status_error_in_images': 'Error in images.',
	'project_status_error_in_options': 'Error in options.',
	'project_status_error_loading_library': 'Failed to import "{0}" functions.',
	'project_status_error_loading_file': 'Failed to access file.',
	'project_status_error_creating_menu': 'Failed to create menu.',
	'project_status_aborted': 'Aborted.',
	'project_status_loading': 'Loading file ...',
	'project_status_loading_file': 'Loading file ... {0} / {1}',
	'project_status_reading_file': 'Reading file ... {0} / {1}',
	'project_status_reading_layers': 'Reading layers ... {0} / {1}',
	'project_status_reading_images': 'Reading images ... {0} / {1}',
	'project_status_ready_no_options': 'No options.',
	'project_status_ready_options': 'Ready.',
	'project_status_ready_options_plural': 'Ready, {0} variants.',
	'project_status_ready_options_singular': 'Ready, {0} variant.',
	'project_status_rendering': 'Rendering ...',
	'project_status_rendering_collage': 'Rendering collage ...',
	'project_status_rendering_batch': 'Rendering ... {0} / {1}',
	'project_status_counting_batch': 'Evaluating ... {0} / {1}',
	'project_status_saving_layers': 'Saving layers ... {0} / {1}',
	'project_status_saving_images': 'Saving images ... {0} / {1}',
	'project_status_saving_render': 'Saving preview ... {0} / {1}',
	'project_status_saving_file': 'Saving file ... {0} / {1}',

	'page_version_link': 'Link to another version of this page.',
	'help_section_link': 'Link to another section of this manual.',
	'external_link': [
		'Link to another site:',
		'{0}',
	],
	'unknown_link': [
		'Unknown link:',
		'{0}',
	],
	'unknown_button': [
		'Unknown button:',
		'{0}',
	],
};
